### Signup route

POST http://localhost:4000/api/signup HTTP/1.1
Content-Type: application/json

{
    "user": {
        "email": "a@b.com",
        "password": "123",
        "name": "deepz"
    }
}

### Ensure authenticated route

GET http://localhost:4000/api/users HTTP/1.1
Content-Type: application/json
authorization: "Bearer SFMyNTY.g2gDYQJuBgDq28Y6fgFiAAFRgA.Z5g7F2ZMM30ZIbpZ8nDpHIUNWqWyhRYJtmPnMs6OBOc"

### Login route

POST http://localhost:4000/api/login HTTP/1.1
Content-Type: application/json

{
    "email": "c@d.com",
    "password": "123"
}